title: Church of Dogs
#logo
description: Canine Devotion Improves Human Emotion
show_downloads: true
remote_theme: pages-themes/cayman@v0.1.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
